### ISSUE TITLE
Requested: Show title instead of captions as option. 

### ISSUE THREAD

**Issue by thriveweb** [thriveweb/photoswipe-masonry-v2#2]
I also would like to show TITLES in photoswipe. Additionally or instead of caption.

**Comment by Jon007** [comment]
There is a specific issue that is happening here:
Photoswipe is only looking at the data-caption="" attribute of the anchor, which is  added to gallery images by photoswipe, but not implemented for the single-photoswipe (or my extension of it).

Photoswipe should be a bit more intelligent to look at eg:
1. a @data-caption
2. a.figcaption innerText --  Wordpress post level override of the image caption
3. a.img @title                 
4. a.img @alt
5. a.href filename   -- the filename of the full-size image
to try harder to get some information to display about the image.

Ideally point 1 should be removed altogether, since these additional photoswipe attributes are not necessary.

**Comment by Jon007** [comment]
photoswipe-masonry.js  this block of code:
				var item = {
					src 	: $href,
					w   	: $width,
					h   	: $height,
					el		: $(this),
					msrc	: $(this).find('img').attr('src'),
					title	: $(this).attr('data-caption')
				}
				items.push(item);
			});
			return items;
		}`
change to eg:
```
            //$img = $(this).find('img');
            $title = $(this).attr('data-caption');
            if (!($title)) {
              $figcaption = $(this).find('figcaption');
              $title = $figcaption.val();
              if (!($title)) {
                $title= $img.attr('title');
                if (!($title)) {
                  $title= $img.attr('alt');
                  if (!($title)) {
                    $title=$href.substring($href.lastIndexOf('/')+1);
                  }
                }
              }
            };

              
            var item = {
              src 	: $href,
              w   	: $width, 
              h   	: $height,
              el		: $(this),
              msrc	: $img.attr('src'),
              title	: $title
            }

```
should do the trick...

**Comment by thriveweb** [comment]
Hi Jon. Thanks so much for helping with the issues and requests. It would be ideal if you made a pull request for these code changes. Are you familiar with git and github? I'm happy to give you any help you need with this work flow!

**Comment by Jon007** [comment]
sure, I was thinking about that but waiting some feedback from you, to agree how do it in a way that would be easiest to merge back in.

A couple of points/questions:

- some of the points should probably be options on the add-in, I'd like to hear your thoughts on that
- fixes to the photoswipe-ui in photoswipe-dist (eg share current image details to facebook rather than current page) should be pushed back to Dmitry Semenov:  are you in touch with him and pulling any update from his end? [again the sharing on the individual image should probably be configurable, to allow people to add different sharing sites or override the parameters]
- have you looked at wooCommerce 2.7 beta: there's actually a video of the photoswipe in use here: https://wordpress.com/read/blogs/96396764/posts/2505
My aim is compatibility with that, and to ensure the site only needs one set of javascript/css to run the image galleries, rather than different ones for different pages.  I haven't checked their code yet, but I don't want to do a lot more work on this without doing that.

**Comment by thriveweb** [comment]
Hey Jon,

Yes, making things optional is always good, especially if it's a new feature. 

For Photoswipe bugs it would be best to make issues here https://github.com/dimsemenov/photoswipe - it looks like there is a few! But you might get more feedback from others. 

I've been meaning to look at the new WooCommerce as we use Photoswipe for https://github.com/thriveweb/wooswipe also.

**Comment by thriveweb** [comment]
Feel free to email me for help with github etc dean@thriveweb.com.au
