### ISSUE TITLE
Serious performance issue reported

### ISSUE THREAD

**Issue by thriveweb** [thriveweb/photoswipe-masonry-v2#26]
See https://wordpress.org/support/topic/serious-performance-issue-3/

**Comment by thriveweb** [comment]
Not seeing this. User needed to rebuild thumbnails I think.

**Comment by Jon007** [comment]
actually no, its not a thumbnail issue, it's the same as we have been discussing on #15 

If you have rebuilt the thumbnails, the plugin still downloads all the thumbnails **and all the full sized images as well **  even though the user has not chosen to open any image.

In the example I gave, a plugin with true lazy loading gave a total page size of 1.7Mb because it only downloads the thumbnails and does not download the full images until the user clicks to expand.
For a similar size gallery, photoswipe-masonry had a page download size of 40Mb because it always tries to download the full size images even if they have not be requested by the user

**Comment by Jon007** [comment]
fix now added to #15

**Comment by thriveweb** [comment]
In this case the user is not using the gallery feature. He was embedding a bunch of single galleries. I'll check out #15

**Comment by Jon007** [comment]
@thriveweb the same code to force load the full size images as part of the page load is present on both the gallery loader and the single file loader.
 - in my pull request merged into one function to abolish the single popup and make one slideshow for the images within the page

**Comment by thriveweb** [comment]
Hi Jon. Please see @vweltje rewrite of the whole plugin. The loading issue should be fixed also :)
